// This file is auto-generated by scripts/sync-brand-theme-from-css.mjs
// Source of truth: app/globals.css (:root brand variables)
// Do not edit manually — run "pnpm sync:brand-theme" after changing globals.css

export const DEFAULT_BRAND_THEME = {
  "brand_primary": "#6d4bdd",
  "brand_primary_2": "#9e94c7",
  "brand_primary_3": "#b9a8fc",
  "brand_secondary": "#f3b42b",
  "brand_success": "#6bd127",
  "brand_success_2": "#80ff2b",
  "brand_danger": "#F8595F",
  "brand_danger_2": "#cc3232"
};
